name: grocery_delivery_boy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.2
  shared_preferences: 
  dio: ^5.4.3+1
  google_maps_flutter: 
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  url_launcher: 


  firebase_messaging: ^15.2.5
  flutter_local_notifications: 
  path_provider: 
  vibration: ^3.1.3
  shimmer: ^3.0.0
  flutter_widget_from_html_core: 
  http: ^1.2.1
  image_picker: 
  flutter_lints: ^5.0.0
  country_code_picker: ^3.0.0
  phone_numbers_parser: ^9.0.3
  dotted_border: ^2.1.0
  firebase_core: ^3.13.0
  cached_network_image: ^3.3.1
  flutter_plugin_android_lifecycle: ^2.0.27
 
  firebase_crashlytics: ^4.3.5
  photo_view: ^0.15.0
  change_app_package_name: 






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
